
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AND COMMA CONSTANT EQX FROM SELECT SPACE STAR TCNAME WHEREQuery : SFW\n             | SFW_no_whereSFW_no_where : SELECT SelList FROM FromListSFW : SELECT SelList FROM FromList WHERE CondSelList : STARSelList : TCNAME COMMA SelListSelList : TCNAMEFromList : TCNAME COMMA FromListFromList : TCNAMECond : TCNAME EQX CONSTANT'
    
_lr_action_items = {'SELECT':([0,],[4,]),'$end':([1,2,3,10,11,15,17,19,],[0,-1,-2,-3,-9,-4,-8,-10,]),'STAR':([4,9,],[6,6,]),'TCNAME':([4,8,9,13,14,],[7,11,7,16,11,]),'FROM':([5,6,7,12,],[8,-5,-7,-6,]),'COMMA':([7,11,],[9,14,]),'WHERE':([10,11,17,],[13,-9,-8,]),'EQX':([16,],[18,]),'CONSTANT':([18,],[19,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'Query':([0,],[1,]),'SFW':([0,],[2,]),'SFW_no_where':([0,],[3,]),'SelList':([4,9,],[5,12,]),'FromList':([8,14,],[10,17,]),'Cond':([13,],[15,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> Query","S'",1,None,None,None),
  ('Query -> SFW','Query',1,'p_expr_query','parser_db.py',17),
  ('Query -> SFW_no_where','Query',1,'p_expr_query','parser_db.py',18),
  ('SFW_no_where -> SELECT SelList FROM FromList','SFW_no_where',4,'p_expr_swf_no_where','parser_db.py',27),
  ('SFW -> SELECT SelList FROM FromList WHERE Cond','SFW',6,'p_expr_swf','parser_db.py',34),
  ('SelList -> STAR','SelList',1,'p_expr_sellist_star','parser_db.py',43),
  ('SelList -> TCNAME COMMA SelList','SelList',3,'p_expr_sellist_first','parser_db.py',49),
  ('SelList -> TCNAME','SelList',1,'p_expr_sellist_second','parser_db.py',56),
  ('FromList -> TCNAME COMMA FromList','FromList',3,'p_expr_fromlist_first','parser_db.py',62),
  ('FromList -> TCNAME','FromList',1,'p_expr_fromlist_second','parser_db.py',69),
  ('Cond -> TCNAME EQX CONSTANT','Cond',3,'p_expr_condition','parser_db.py',75),
]
